config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :users
  resources :items
  resources :stores
  resources :quotes
  # Role and Permission related
  resources :permissions
  resources :roles do
    get  'update_permissions'
    post 'save_permissions'
    patch 'save_permissions'
  end

  get '/users/:id/roles', controller: 'users', action: 'show_roles', as: 'show_roles'
  match '/users/:id/save_roles', to:'users#save_roles', via: [:patch, :post], as: 'user_roles_save'
  match '/users/:id/update_approve', to:'users#update_approve', via: [:patch, :post], as: 'user_approve'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/add_quotes/', controller: 'quotes', action: 'add_quote', as: 'add_quote'
end

app/models/store.rb
class Store < ApplicationRecord
  include Formatters
  self.table_name = 'tbl_stores'
  has_paper_trail versions: { class_name: 'StoreVersion' }

  before_validation(on: [:create, :update]) do
    #self.name = self.name.downcase.strip unless self.name.blank?
    # Apply formatting
    transform_downcase [:store_type]
    strip_whitespace [:store_type]
  end


  private

    # Specifies the fields that have some auto formatting, we use this to distinqush
    # formatting changes vs real data changes when updates occur
    def formatted_fields
      {name: ['strip', 'downcase'], description: ['strip']}
    end
end

app/models/store_type.rb
class StoreType < ApplicationRecord
  include Formatters
  self.table_name = 'store_types'


  
  private

    # Specifies the fields that have some auto formatting, we use this to distinqush
    # formatting changes vs real data changes when updates occur
    def formatted_fields
      {name: ['strip', 'downcase'], description: ['strip']}
    end
end

app/controllers/stores_controller.rb
# The stores Controller class facilitates the crud actions on
# stores model.
# CRUD actions are triggered from within the store index page
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action do set_active_main_menu "stores" end
  # after_action :verify_authorized, only: [:update, :create, :destroy]
  # after_action :verify_policy_scoped, only: :index
  # skip_after_action :verify_authorized
  # after_action :verify_authorized, only: [:index, :create, :update, :destroy]
  before_action :retrieve_store, only: [:show, :edit, :update, :destroy]
  before_action :retrieve_user_permission, only: [:index]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # rescue_from ActionController::UnknownFormat, with: :Unknown_Format
  rescue_from ActiveRecord::StaleObjectError, with: :stale_object_error
  rescue_from ActiveRecord::InvalidForeignKey, with: :invalid_foreign_key

  def index
    @stores = Store.all
    unless search_store_params.blank?
      @stores = Store.all
      store_num = search_store_params["store_num"] unless search_store_params["store_num"].blank?
      unless store_num.blank?
        @stores = @stores.where("store_num = ?", store_num)
      end
      city = search_store_params["city"] unless search_store_params["city"].blank?
      unless city.blank?
        @stores = @stores.where("city = ?", city)
      end
      state_region = search_store_params["state_region"] unless search_store_params["state_region"].blank?
      unless state_region.blank?
        @stores = @stores.where("state_region = ?", state_region)
      end
    store_type_id = search_store_params["store_type_id"] unless search_store_params["store_type_id"].blank?
      unless store_type_id.blank?
        @stores = @stores.where("store_type_id = ?", store_type_id)
      end
      status = search_store_params["status"] unless search_store_params["status"].blank?
        unless status.blank?
          @stores = @stores.where("status = ?", status)
        end
      @stores = @stores.order("store_num")
    end
  end

## Add New Store
  def new
    @store = Store.new
    @types = StoreType.all
    @states = Store.order(:state_region).pluck(:state_region).uniq
    @status = Store.order(:status).pluck(:status).uniq
    @error_msg = @store.errors.messages
  end

  # Create saves the stores
  def create
    @store = Store.new(store_params)

    # if authorize @permission
      @store.set_modifiers current_user
      if @store.save
        flash[:context] = "inline"
        flash[:success] = "Store '#{@store.store_num}' successfully created."
        flash[:success_id], flash[:row_id] = @store.id, @store.id
        render 'row'
      else
        flash.now[:error] = @store.errors.full_messages
        @error_msg = @store.errors.messages
        render 'new'
      end
    # end
  end
  def show
    @store = Store.find(params[:id])
    @store_type = StoreType.find(@store.store_type_id)
  end

  def edit
    @store = Store.find(params[:id])
    @types = StoreType.all
    @error_msg = @store.errors.messages
  end

  def update
    @store = Store.find(params[:id])
    # if authorize @permission
      changed = @store.contains_changes?(store_params)
      @store.set_modifiers current_user if changed
      if changed && @store.update(store_params)
        flash[:context] = "inline"
        flash[:success] =  "Store '#{@store.store_num}' successfully updated."
        flash[:success_id], flash[:row_id] = @store.id, @store.id
        render 'row'
      else
        @store.errors[:base] << "No changes made" unless changed
        flash.now[:error] = @store.errors.full_messages
        @error_msg = @store.errors.messages
        render 'edit'
      end
    # end
  end

  # Destroy deletes the permission record
    def destroy
      @store = Store.find(params[:id])
      # if authorize @permission
      if @store.destroy
        flash.now[:notice] = "Store '#{@store.store_num}' successfully deleted."
        render 'row'
      end
    end

    private

    # Retrieves the country record
    def retrieve_store
      @store = Store.find(params[:id])
    end

    def retrieve_user_permission
      @types = StoreType.all
      @states = Store.select(:state_region).order(:state_region).distinct
      @status = Store.select(:status).order(:status).distinct
      @can_create = policy(Store).create?
      @can_edit = policy(Store).update?
      @can_show = policy(Store).show?
    end


    # Whitelist the parameters we know/expect
    def store_params
      params.require(:store).permit(:store_num, :address, :city, :postcode, :state_region,:store_type_id, :status,
        :phone_num, :district_manager, :dm_contact_num, :is_halal, :is_cafe, :num_of_drivethru,:archived, :lock_version)
    end

    # Whitelist the parameters we know/expect for search, array must be at the end of the list
    def search_store_params
      params.permit(:store_num, :address, :city, :postcode, :state_region, :status,
        :phone_num, :district_manager, :dm_contact_num, :archived, :store_type_id)
    end
end

app/views/stores/_form.html.erb
<!-- Modal -->
<div class="modal-dialog  modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title" id="modalTilte">Add Store</h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_for(:store, remote: true, url: url, method: method, html: {class: 'form-horizontal'}) do |f| %>
        <%= f.hidden_field :lock_version %>
          <%= render partial: 'layouts/flash_messages', locals: {:context => :modal}  %>
          <div class="form-group required <%= @error_msg[:store_num].blank? ? "" : "has-error" %>">
            <%= f.label :store_num, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :store_num, {autofocus: true, class: "form-control", required: true} %>
            </div>
          </div>

          <div class="form-group required <%= @error_msg[:address].blank? ? "" : "has-error" %>">
            <%= f.label :address, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :address, {class: "form-control", required: true} %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:city].blank? ? "" : "has-error" %>">
            <%= f.label :city, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :city, {class: "form-control", required: true} %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:postcode].blank? ? "" : "has-error" %>">
            <%= f.label :postcode, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :postcode, {class: "form-control", required: true} %>
            </div>
          </div>

          <div class="form-group required<%= @error_msg[:store_type_id].blank? ? "" : "has-error" %>">
            <%= f.label :Store_Type, class: "control-label col-md-3" %>
              <% store_type_attrs = {:class=>'form-control', id: 'store_type_select', prompt: "Please select", required: true} %>
              <% store_type_sel = @selected_store_type.blank? ? '' : @selected_store_type %>
              <div class="col-md-7">
                <%= select_tag("store[store_type_id]",
                  options_from_collection_for_select(@types, "id", "name", store_type_sel), store_type_attrs) %>
              </div>
          </div>

          <div class="form-group required<%= @error_msg[:state_region].blank? ? "" : "has-error" %>">
            <%= f.label :State_Region, class: "control-label col-md-3" %>
              <% state_region_attrs = {:class=>'form-control', id: ' state_region_select', prompt: "Please select", required: true} %>
              <% state_region_sel = @selected_state_region.blank? ? '' : @selected_state_region %>
              <div class="col-md-7">
                <%= select_tag("store[state_region]",
                  options_for_select(@states, state_region_sel), state_region_attrs) %>
              </div>
          </div>

          <div class="form-group required<%= @error_msg[:state_region].blank? ? "" : "has-error" %>">
            <%= f.label :Status, class: "control-label col-md-3" %>
              <% store_status_attrs = {:class=>'form-control', id: ' state_region_select', prompt: "Please select", required: true} %>
              <% store_status_sel = @selected_sstore_status.blank? ? '' : @selected_store_status %>
              <div class="col-md-7">
                <%= select_tag("store[state_region]",
                  options_for_select(@status, store_status_sel), store_status_attrs) %>
              </div>
          </div>

          <div class="form-group required <%= @error_msg[:state_region].blank? ? "" : "has-error" %>">
            <%= f.label :State_Region, class: "control-label col-md-3" %>
            <div class="col-md-7">
            <%= f.select :state_region, {'Select State Region': "", 'NSW': "NSW", 'QLD': "QLD", 'NT':"NT", 'WA': "WA", 'ACT': "ACT", 'TAS': "TAS", 'VIC': "VIC", 'SA': "SA", 'QLD South': "QLD South", 'QLD North': "QLD North"}, {class: "form-control", required: true}%>
            </div>
          </div>

          <div class="form-group required <%= @error_msg[:status].blank? ? "" : "has-error" %>">
            <%= f.label :Status, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.select :status, {'Select Store Status': "", 'Trading': "Trading", 'Construction': "Construction", 'TempClosure': "Temp Closure"}, {class: 'form-control selectpicker', required: true} %>
            </div>

          </div>

          <div class="form-group required <%= @error_msg[:phone_num].blank? ? "" : "has-error" %>">

            <%= f.label :Phone_Number, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :phone_num, {class: "form-control", placeholder: "1234 567 890",
                pattern: "^\({0,1}((0|\+61)(2|4|3|7|8)){0,1}\){0,1}( |-){0,1}[0-9]{2}( |-){0,1}[0-9]{2}( |-){0,1}[0-9]{1}( |-){0,1}[0-9]{3}$", required: true} %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:district_manager].blank? ? "" : "has-error" %>">

            <%= f.label :district_manager, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :district_manager, {class: "form-control", required: true} %>
            </div>
          </div>

          <div class="form-group required <%= @error_msg[:dm_contact_num].blank? ? "" : "has-error" %>">

            <%= f.label :District_Manager_contact_number, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :dm_contact_num, {class: "form-control", placeholder: "1234 567 890",
                pattern: "^\({0,1}((0|\+61)(2|4|3|7|8)){0,1}\){0,1}( |-){0,1}[0-9]{2}( |-){0,1}[0-9]{2}( |-){0,1}[0-9]{1}( |-){0,1}[0-9]{3}$", required: true} %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:num_of_drivethru].blank? ? "" : "has-error" %>">
            <%= f.label :DriveThru_Number, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.text_field :num_of_drivethru, {class: "form-control", required: true} %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:is_halal].blank? ? "" : "has-error" %>">
            <%= f.label :Halal, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.check_box :is_halal, :data => { :size=>'medium',
                 'on-color'=>'success', 'on-text'=> "#{t('yes').upcase}",
                  'off-text'=> "#{t('no').upcase}" } %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:is_cafe].blank? ? "" : "has-error" %>">
            <%= f.label :Cafe, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.check_box :is_cafe, :data => { :size=>'medium',
                 'on-color'=>'success', 'on-text'=> "#{t('yes').upcase}",
                  'off-text'=> "#{t('no').upcase}" } %>
            </div>
          </div>
          <div class="form-group required <%= @error_msg[:archived].blank? ? "" : "has-error" %>">
            <%= f.label :archived, class: "control-label col-md-3" %>
            <div class="col-md-7">
              <%= f.check_box :archived, :data => { :size=>'medium',
                 'on-color'=>'success', 'on-text'=> "#{t('yes').upcase}",
                  'off-text'=> "#{t('no').upcase}" } %>
            </div>
          </div>

          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-warning active">
              <input type="radio" name="options" id="option1" autocomplete="off" checked> Active
            </label>
            <label class="btn btn-warning" style="margin-left: 10px;">
              <input type="radio" name="options" id="option2" autocomplete="off"> Radio
            </label>
            <label class="btn btn-warning">
              <input type="radio" name="options" id="option3" autocomplete="off"> Radio
            </label>
          </div>

          <div class="btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-secondary active">
            <input type="checkbox" checked autocomplete="off"> Checked
            </label>
          </div>

          <div class="form-group">
            <div class="col-md-12 col-md-offset-2">
              <span class="help-block"><span class="mandatory">*</span> denotes required field</span>
            </div>
          </div>

        <div class="modal-footer">
          <div class="actions col-md-12 text-center">
            <%= f.submit submit_label, {class: "btn btn-success"} %>
            <%= f.button 'Cancel', {class: "btn btn-info", "data-dismiss" => "modal", type: "button", id: "btnCancel"} %>
             <% if controller.action_name == "edit" %>
                <%= f.button 'Delete', {id: "delete", class: "btn btn-danger", "type" => "button", "data-toggle" => "collapse", "data-target" => "#confirm-delete-pane"} %>
               <div id="confirm-delete-pane" class="confirm-delete-pane collapse col-md-12 text-center">
                 <p>Please confirm that you want to delete store: <%= @store.store_num %></p>
                 <%= link_to 'Confirm Delete', store_path(@store.id),
                   {method: 'delete', remote: true, id: 'confirm-delete', class: 'btn btn-danger'} %>
               </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/stores/_row.html.erb
<% unless stores.blank? %>
  <% stores.each do |cl| %>
  <tr id=<%= cl.id %> >
    <td><%= cl.id %></td>
    <td style="text-align:right"><%= cl.store_num %></td>
    <td><%= cl.address %></td>
    <td><%= cl.city %></td>
    <td style="text-align:right" ><%= cl.postcode %></td>
    <td><%= cl.state_region %></td>
    <td><% if cl.store_type_id != nil%>
      <%= store_types.find(cl.store_type_id).name %>
      <% end  %></td>
    <td><%= cl.status %></td>
    <td style="text-align:right"><%= cl.phone_num %></td>
    <td><%= cl.district_manager %></td>
    <td style="text-align:right"><%= cl.dm_contact_num %></td>
    <td><%= cl.is_halal==0 ? "N" : "Y" %></td>
    <td><%= cl.is_cafe==0 ? "N" : "Y" %></td>
    <td style="text-align:right"><%= cl.num_of_drivethru %></td>
    <td style="text-align:center">
      <div>
        <% if @can_show == true %>
          <%= link_to 'Show',  store_path(cl), {
            remote: true, "data-target" => "#modal-window",
            class: "btn btn-sm btn-primary"} %>
          <% end %>
        <% if @can_edit == true  %>
          <%= link_to 'Edit', edit_store_path(cl), {
          remote: true, "data-target" => "#modal-window",
          class: "btn btn-sm btn-warning"} %>
        <% end %>
      </div>
    </td>
  </tr>
  <% end %>
<% end %>

app/views/stores/_row_store.html.erb
<%# this is trigger only after either create or  update or show %>
<% unless store.blank? %>
<tr <tr style='background-color: #d4edda;' id=<%= store.id %> >
  <td style="text-align:right"><%= store.id %></td>
  <td style="text-align:right"><%= store.store_num %></td>
  <td><%= store.address %></td>
  <td><%= store.city %></td>
  <td style="text-align:right" ><%= store.postcode %></td>
  <td><%= store.state_region %></td>
  <td><%= store.status %></td>
  <td style="text-align:right"><%= store.phone_num %></td>
  <td><%= store.district_manager %></td>
  <td style="text-align:right"><%= store.dm_contact_num %></td>
  <td><%= store.is_halal==0 ? "N" : "Y" %></td>
  <td><%= store.is_cafe==0 ? "N" : "Y" %></td>
  <td><%= store.num_of_drivethru %></td>
  <td style="text-align:center">
    <div>
      <%= link_to 'Show',  store_path(store.id), {
        remote: true, "data-target" => "#modal-window",
        class: "btn btn-sm btn-primary"} %>

      <%= link_to 'Edit', edit_store_path(store.id), {
        remote: true, "data-target" => "#modal-window",
        class: "btn btn-sm btn-warning"} %>
    </div>
  </td>
</tr>
<% end %>

app/views/stores/_show.html.erb
<!-- Modal -->
  <div class="modal-dialog  modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="modalTilte">Store  Number: <%= @store.store_num %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class='modal-body'>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Address</div>
          <div class="col-md-8"><%= @store.address %></div>
        </div>

        <div class="field-group-inline row">
          <div class="field-label col-md-3">City</div>
          <div class="col-md-8"><%= @store.city %></div>
        </div>

        <div class="field-group-inline row">
          <div class="field-label col-md-3">Postcode</div>
          <div class="col-md-8"><%= @store.postcode %></div>
        </div>

        <div class="field-group-inline row">
          <div class="field-label col-md-3">State Region</div>
          <div class="col-md-8"><%= @store.state_region %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Store Type</div>
          <div class="col-md-8"><%= @store_type.name %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Status</div>
          <div class="col-md-8"><%= @store.status %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Phone Number</div>
          <div class="col-md-8"><%= @store.phone_num %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">District Manager</div>
          <div class="col-md-8"><%= @store.district_manager %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Manager Contact Number</div>
          <div class="col-md-8"><%= @store.dm_contact_num %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Halal</div>
          <div class="col-md-8"><%= @store.is_halal ==0? "No" : "Yes" %> </div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Cafe</div>
          <div class="col-md-8"><%= @store.is_cafe ==0? "No" : "Yes" %></div>
        </div>
        <div class="field-group-inline row">
          <div class="field-label col-md-3">Drivethru Number</div>
          <div class="col-md-8"><%= @store.num_of_drivethru %></div>
        </div>


        <div class="field-group-inline row" data-field="created">
          <div class="field-label col-md-3">Created at</div>
          <div class="col-md-8">
            <%= @store.created_at.to_s(:medium) %> by <%= @store.created_by %>
          </div>
        </div>
      <div class="field-group-inline row" data-field="updated">
        <div class="field-label col-md-3">Updated at</div>
        <div class="col-md-8">
          <%= @store.updated_at.to_s(:medium) %> by <%= @store.updated_by %>
        </div>
      </div>
      <div class="modal-footer">
        <div class="actions col-md-12 text-center">
          <%= button_tag 'Close', {class: "btn btn-default", "data-dismiss" => "modal", id: 'btnClose'} %>
        </div>
      </div>
    </div>
  </div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#btnClose').click(function() {
       $("#modal-window").modal("hide");
    });
  });
</script>

app/views/stores/edit.js.erb
var contents =
  "<%= escape_javascript(render partial: 'stores/form', locals: {url: store_path, submit_label: 'Update', heading_prefix: 'Edit', method: 'patch'}) %>";

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action')
})

$("#modal-window").html(contents);

// Listen for delete button being clicked and disable it after the
// confirm delete pane is shown
$('.confirm-delete-pane').on("shown.bs.collapse", function() {
  $("#delete").attr("disabled", "disabled");
});

app/views/stores/index.html.erb
<div class="container-fluid">
  <%= form_tag(stores_path, method: 'get', id: 'search_store') do |f| %>
    <h1>
      Stores
    </h1>
    <hr>
    <div>
      <% if @can_create == true %>
        <%= link_to "Add Store", new_store_path,
          {'class' => 'btn btn-success', 'remote' => true,
            'data-target' => '#myModal', 'id' => 'Add_btn'} %>

      <% end %>
      <% if @can_create == true %>
        <%= link_to "Import Store", new_store_path,
          {'class' => 'btn btn-warning', 'remote' => true,
            'data-target' => '#myModal', 'id' => 'Add_btn'} %>
      <% end %>
        <hr>
    </div>

    <div class="row">
      <div class="col-sm-2">
        <%= search_field_tag :store_num, nil, class: 'form-control',
        placeholder: 'Store Number', value: params[:store_num] %>
      </div>
      <div class="col-sm-2">
        <%= search_field_tag :city, nil, class: 'form-control',
        placeholder: 'City', value: params[:city] %>
      </div>
      <div class="col-sm-2">
        <%= select_tag :state_region, options_from_collection_for_select(@states, "state_region", "state_region",
          params[:state_region].to_s), {prompt: "State Region", class: 'form-control selectpicker'} %>
      </div>
      <div class="col-sm-2">
        <%= select_tag :store_type_id, options_from_collection_for_select(@types,"id", "name",
          params[:store_type_id].to_s), {prompt: "Store Type", class: 'form-control selectpicker'} %>
      </div>
      <div class="col-sm-2">
        <%= select_tag :status, options_from_collection_for_select(@status, "status", "status",
          params[:status].to_s), {prompt: "Store Type", class: 'form-control selectpicker'} %>
      </div>
      <div class="col-sm-2">
          <%= submit_tag "Submit", class: 'btn btn-primary btn-md', :name => nil,
            id: 'log_submit_btn' %>
          <input type="button" value="Clear" id="clear_filter"
            class="btn btn-danger btn-md">
      </div>
    </div>
  <% end %>
  <br>
  <% unless @stores.blank? %>
    <table class="table table-bordered table-hover table-striped" id="tblStore">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Store Number </th>
          <th scope="col">Address</th>
          <th scope="col">City</th>
          <th scope="col">Postcode</th>
          <th scope="col">State Region</th>
          <th scope="col">Store Type</th>
          <th scope="col">Status</th>
          <th scope="col">Phone no.</th>
          <th scope="col">District Manager</th>
          <th scope="col">Manager Contct No.</th>
          <th scope="col">Halal</th>
          <th scope="col">Cafe</th>
          <th scope="col">No. of Drivethru</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "row",  locals: { stores: @stores, store_types: @types} %>
      </tbody>
    </table>
  <% end %>
<div>

  <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
  <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>


<script type="text/javascript">
  $(document).ready(function() {
    $('#tblStore').DataTable();
    // $('#tblItem').DataTable({
    //   "dom": 'lBfrtip',
    //   buttons: [
    //     {
    //       extend: 'excelHtml5',
    //       exportOptions: {
    //           columns: [ 0, 1, 2, 3, 4, 5 ]
    //       }
    //     },
    //     {
    //       extend: 'pdfHtml5',
    //       exportOptions: {
    //         columns: [ 0, 1, 2, 3, 4, 5 ]
    //       }
    //     }
    //   ]
    // });

  });

  $('#clear_filter').click(function() {
    $('#tblStore').DataTable().clear().draw();
    $("#store_num").val('');
    $("#city").val('');
    $("#state_region").val($("#state_region option:first").val());
    $("#store_type_id").val($("#store_type_id option:first").val());
  });

</script>

app/views/stores/new.js.erb
var contents =
  "<%= escape_javascript(render partial: 'stores/form', locals: {url: stores_path, submit_label: 'Create', heading_prefix: 'Add', method: 'post'}) %>";

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);

app/views/stores/row.js.erb
// close the modal
$("#modal-window").modal("hide");
$(".row.row-msg").fadeOut().remove();
$(".messages").fadeOut().remove();
<% if controller.action_name == "index" %>
  // Placeholder maybe when we update states belonging to countries this changes
<% elsif controller.action_name == "create" %>
  var store = <%= @store.to_json.html_safe %>;

  $('#tblStore tbody tr:first').before("<%= escape_javascript(render partial: 'row_store', locals: { store: @store} ) %>");
<% elsif controller.action_name == "update" %>
  var store = <%= @store.to_json.html_safe %>;
  // $('table#tblstore tr#'<%= @store.to_json.html_safe %>).remove();
 $("#"+ store["id"] +"").replaceWith("<%= escape_javascript(render partial: 'row_store', locals: { store: @store} ) %>");
<% elsif controller.action_name == "destroy" %>
  var store = <%= @store.to_json.html_safe %>;
  $("#"+ store["id"] +"").fadeOut("normal", function() {
      $(this).remove();
  });
<% end %>

app/views/stores/show.js.erb
var contents =
  "<%= escape_javascript(render partial: 'stores/show') %>";

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);