config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :users
  resources :items
  resources :stores
  resources :quotes
  # Role and Permission related
  resources :permissions
  resources :roles do
    get  'update_permissions'
    post 'save_permissions'
    patch 'save_permissions'
  end

  get '/users/:id/roles', controller: 'users', action: 'show_roles', as: 'show_roles'
  match '/users/:id/save_roles', to:'users#save_roles', via: [:patch, :post], as: 'user_roles_save'
  match '/users/:id/update_approve', to:'users#update_approve', via: [:patch, :post], as: 'user_approve'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/add_quotes/', controller: 'quotes', action: 'add_quote', as: 'add_quote'
end

app/models/permission.rb
# This is the Permission model. It stores all the permission.
class Permission< ApplicationRecord
  include Formatters
  has_paper_trail versions: { class_name: 'PermissionVersion' }

  before_validation(on: [:create, :update]) do
    #self.name = self.name.downcase.strip unless self.name.blank?
    # Apply formatting
    transform_downcase [:name]
    strip_whitespace [:name, :description]
  end

  has_and_belongs_to_many :roles, :join_table => :role_permissions
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :group_name, :description, presence: true
  before_destroy :has_permission_been_assigned?

  # Checks whether the permission has been assigned
  def has_permission_been_assigned?
    RolePermission.find_by_permission_id(self.id).blank? ? false : true
  end

  private

  # Specifies the fields that have some auto formatting, we use this to distinqush
  # formatting changes vs real data changes when updates occur
  def formatted_fields
    {name: ['strip', 'downcase'], description: ['strip']}
  end

end

app/models/user.rb
class User < ApplicationRecord
    include Formatters
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
   :validatable, :confirmable, :lockable, :timeoutable
  attr_writer :login
  after_create :send_admin_mail
  has_many :user_role_locations

  # after_create :set_default_role
  mattr_accessor :add_message
  mattr_accessor :updated_message
  mattr_accessor :remove_message

  def login
   @login || self.email
  end

  # Fetch the current user
  def self.current
    Thread.current[:user]
  end

  # Assign the current user.
  def self.current=(user)
    Thread.current[:user] = user
  end
  # Find the user from ldap response
  def self.from_omniauth(auth)
    where(provider: auth['provider'], uid: auth['info']['nickname']).first
  end

  # Returns full name
  def full_name
    "#{self.first_name} #{self.last_name}"
  end



  def send_admin_mail
    AdminMailer.new_user_waiting_for_approval(email).deliver
  end


  # Checking if user has any roles
  def has_roles?
    if self.user_role_locations.blank?
      false
    else
      true
    end
  end
  # This methods checks if user password expired
  # After user login, the sign_in_count is updated to 1 immediately after first login.
  # When set_password is run, there is an option to force non-ldap user to change password
  # when first time login (by setting the password_change_at to a very old date)
  # Hence do not use sign_in_count to force user to change password here.
  def password_expired?
    # return false if self.provider == 'ldap'     # password expiry validation is not for ldap users

    exp_pwd_after = EXPIRE_PASSWORD_AFTER

    pwd_exp_date = (self.password_changed_at.blank? ? self.created_at : self.password_changed_at) + exp_pwd_after

    pwd_expired = (pwd_exp_date.to_date < Time.now.to_date) ? true : false

    return pwd_expired
  end

  # validate password complexity
  def validate_password_complexity

    if self.password.blank?
      return
    end

    pwd_regexpstr = PASSWORD_REGEXPSTR

    if pwd_regexpstr.match(password).blank?
      self.errors[:password] << "must contain 3 out of these 4 groups: big letters, small letters, digits, and symbols from !@#$%^&*()"
      return
    end

    [self.first_name, self.last_name, self.middle_name, self.preferred_name].each do |name|
      if name.blank? == false && (password.downcase.include? name.downcase)
        self.errors[:password] << "cannot include user name"
        break
      end
    end
  end

 def has_permission_where permission, full_object = false, all_levels = false
   p_id = Permission.find_by(name: permission).id

   # FYI in this case URL = user role locations
   urls = User
     .select("users.id, user_role_locations.id as url_id, user_role_locations.role_id")
     .joins(:user_role_locations => {:role => :permissions})
     .where("permissions.id = ? AND users.id = ?", p_id, self.id)
   url_ids  = urls.pluck("user_role_locations.id")
 end

 def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

 def active_for_authentication?
    super && approved?
  end

  def inactive_message
    approved? ? super : :not_approved
  end

  # Role_ids is a hash where key is equal to role_id and value is equal to end_date
  # or nil if not end_dated
  def save_user_roles role_ids = [], end_dates = [], full_name

    unless role_ids.blank?
      loc = self.user_role_locations.where("end_date is ? OR end_date > ?", nil, Time.now).order(:role_id)
      selected_roles = Role.where(:id => role_ids)
      selected_roles_id_array = []
      existing_role_id_array = []
      new_role_id_array = []
      new_roles_end_date = {}
      allRoles = Role.all.to_a
      record_removed = ""
      record_added = ""
      record_updated = ""

      role_ids.each do |r|
        unless r.blank?
          new_roles_end_date[r.to_s] = end_dates[r.to_s]
        end
      end

      selected_roles.each do |r|
        selected_roles_id_array << r.id
      end

      loc.each do |l|

        existing_role_id_array << l.role_id
        match_role = selected_roles_id_array.any? {|rid| rid == l.role_id}
        unless l.end_date.blank?
          match_end_date = (new_roles_end_date[l.role_id.to_s] == (l.end_date.to_time).strftime("%d/%m/%Y %H:%M"))
        else
          match_end_date = (new_roles_end_date[l.role_id.to_s] == l.end_date)
        end

        current_role = allRoles.detect{|c| c.id == l.role_id}
        if match_role
          # leave only or check for end_date to update
          if new_roles_end_date[l.role_id.to_s].blank?
            l.end_date = nil
          else
            l.end_date = DateTime.parse new_roles_end_date[l.role_id.to_s].to_s
          end

          unless match_end_date
            record_updated = record_updated.blank? ? "'" + current_role.name.to_s + "'" : record_updated + ", '" + current_role.name.to_s + "'"
          end
          l.updated_by = full_name
          l.save

        else
          record_removed = record_removed.blank? ? "'" + current_role.name.to_s + "'" : record_removed + ", '" + current_role.name.to_s + "'"
          l.destroy
        end
      end

      if record_removed.include? ","
        record_removed = record_removed + " roles removed for '#{self.full_name}'"
      elsif !record_removed.blank?
        record_removed = record_removed + " role removed for '#{self.full_name}'"
      end

      if record_updated.include? ","
        record_updated = record_updated + " roles successfully updated for '#{self.full_name}'"
      elsif !record_updated.blank?
        record_updated = record_updated + " role successfully updated for '#{self.full_name}'"
      end

      new_role_id_array = (selected_roles_id_array - existing_role_id_array).uniq
      new_role_id_array.each do |r|
        selected_end_date = nil
        current_role = allRoles.detect{|c| c.id == r}
        if new_roles_end_date[r.to_s].blank? == false
          selected_end_date =  DateTime.parse new_roles_end_date[r.to_s].to_s
        end

        rl = UserRoleLocation.create!(:user_id => self.id,
            :role_id => r ,
            :end_date => selected_end_date,
            :created_by => full_name,
            :updated_by => full_name
            )

        record_added = record_added.blank? ? "'" + current_role.name.to_s + "'" : record_added + ", '" + current_role.name.to_s + "'"
      end

      if record_added.include? ","
        # record_added = "Added " + record_added + " Roles"
        record_added = record_added + " roles successfully added for '#{self.full_name}'"
      elsif !record_added.blank?
        record_added = record_added + " role successfully added for '#{self.full_name}'"
      end
		end
    self.add_message = record_added.blank? ? "" : record_added
    self.remove_message = record_removed.blank? ? "" : record_removed
    self.updated_message = record_updated.blank? ? "" : record_updated
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action do set_active_main_menu "users" end
    before_action :set_current_user
    after_action :verify_authorized, only: [:index, :create, :update, :destroy, :update_approve, :save_roles]
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
    rescue_from ActionController::UnknownFormat, with: :Unknown_Format


  def index
    authorize User
    @users = User.all
    unless search_user_params.blank?
      @users = User.all
      first_name = search_user_params["first_name"] unless search_user_params["first_name"].blank?
      unless first_name.blank?
        @users = @users.where("first_name = ?", first_name)
      end

      last_name = search_user_params["last_name"] unless search_user_params["last_name"].blank?
      unless last_name.blank?
        @users = @users.where("last_name = ?", last_name)
      end

      email = search_user_params["email"] unless search_user_params["email"].blank?
      unless email.blank?
        @users = @users.where("email = ?", email)
      end

      approved = search_user_params["approved"] unless search_user_params["approved"].blank?
      unless approved.blank?
        approved = (approved.downcase == "true") ? 1 : 0
        @users = @users.where("approved = ?", approved)
      end
      @users = @users.order("first_name", "last_name")
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def show_roles
    @user = User.find(params[:id])
    authorize @user
    @users = User.joins(:user_role_locations).where("user_id =? and (end_date is ? or end_date>?) ", params[:id], nil, Date.today)
    @role_names = {}
    @allroles = Role.all
    @existing_roles = @user.has_roles? ? @user.user_role_locations.where("end_date is ? OR end_date > (?)",
      nil, DateTime.now.to_date).order(:id).pluck(:role_id, :end_date) : []
    Role.select(:id, :name).all.map{|r| @role_names[r.id] = r.name}
  end

  def update_approve
    authorize User
    @user = User.find(params[:id])
    if @user.approved == 0 then
      @user.update(approved: 1)
    else
      @user.update(approved: 0)
    end
  end

# Find the role id first
# Based on role_id delete eveything from role_permissions table
# Add all the permission checked in the forms to the role_permissions table
def save_roles
  @user = User.find(params[:id])
  authorize @user
  if user_role_params[:role_ids]
    if @user.save_user_roles(user_role_params[:role_ids], user_role_params[:end_dates], current_user.full_name)
      flash.now[:context] = "inline"
      flash.now[:success] = []
      flash.now[:success] << @user.add_message unless @user.add_message.blank?
      flash.now[:success] << @user.remove_message unless @user.remove_message.blank?
      flash.now[:success] << @user.updated_message unless @user.updated_message.blank?
      flash.now[:new_location] = user_role_params[:new_location]
      render "row"
    else
      flash.now[:error] = @user.errors.full_messages
      @error_msg = @user.errors.messages
      render "edit_user_roles"
    end
  else
    # TODO flash error
  end
end


  private

    # Whitelist the parameters we know/expect for search, array must be at the end of the list
    def search_user_params
      params.permit(:id, :first_name, :last_name, :email, :approved)
    end

    def user_role_params
      roles = []
      Role.all.pluck(:id).map{|r| roles << r.to_s}
      params.require(:user).permit(:name, :user_id, :lock_version, :reporting_group_id, :new_location, end_dates: [roles], role_ids: [])
    end
end

app/views/users/_approved.html.erb
<% status = nil %>
<% status_to_change = nil %>
<% if data.approved == 0 %>
  <% status = "Disapprove" %>
  <% status_to_change = "Approve" %>
  <button type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#statusModal-<%= data.id %>">
    Approve
  </button>
<% else %>
  <% status = "Approve" %>
  <% status_to_change = "Disapprove" %>
  <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#statusModal-<%= data.id %>">
    Diapprove
  </button>
<% end %>

<div class="modal fade" id="statusModal-<%= data.id %>" tabindex="-1" role="dialog" aria-labelledby="Set Status" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header btn-primary">
        <h4> <class="modal-title" id="myModalLabel">Approve Confirmation</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure about changing the status from <b><%= status %> </b> to <b><%= status_to_change %></b>?
      </div>
      <div class="modal-footer">
        <%= link_to "Yes", user_approve_path(data.id), {class: 'btn btn-sm btn-danger', remote: true, id: 'btnYes', method: "post"} %>
        <%= link_to "No", "javascript:void(0)", {class: 'btn btn-sm btn-warning','data-dismiss': "modal"} %>
      </div>
    </div>
  </div>
</div>

<script>
  $("#statusModal-<%= data.id %>").appendTo('body');
</script>

app/views/users/_row.html.erb
<% unless users.blank? %>
  <% users.each do |cl| %>
    <tr id=<%= cl.id %> >
      <td><%= cl.id %></td>
      <td><%= cl.first_name %></td>
      <td><%= cl.last_name %></td>
      <td><%= cl.email %></td>
      <td><%= cl.approved == 1? "True" : "False" %></td>
      <td><%= cl.confirmed_at %></td>
      <td style="text-align:center">
        <div>
          <% if policy(User).show? %>
            <%= link_to 'Show', user_path(cl), { remote: true, "data-target" => "#modal-window",
              class: "btn btn-sm btn-primary"} %>
          <% end %>
          <% if policy(User).show_roles? %>
            <%= link_to "Roles", show_roles_path(cl),  {
              remote: true,
              'data-target' => '#modal-window', 'class' => 'btn btn-primary btn-sm'} %>
          <% end %>
          <% if policy(User).approve_user? %>
            <%= render partial: "approved",  locals: {data: cl} %>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/users/_row_item.html.erb
<% unless user.blank? %>
  <tr id=<%= user.id %> >
    <td><%= user.id %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.approved == 1? "True" : "False" %></td>
    <td><%= user.confirmed_at %></td>
    <td style="text-align:center" id=approved-<%= user.id%>
      <div>
        <% if policy(User).show? %>
        <%= link_to 'Show', user_path(user), { remote: true, "data-target" => "#modal-window",
          class: "btn btn-sm btn-primary"} %>
        <% end %>
        <% if policy(User).show_roles? %>
          <%= link_to "Roles", show_roles_path(user),  {
            remote: true,
            'data-target' => '#modal-window', 'class' => 'btn btn-primary btn-sm'} %>
        <% end %>
        <% if policy(User).approve_user? %>
          <%= render partial: "approved",  locals: {data: user} %>
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/users/_show.html.erb

<div class="modal-dialog  modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title" id="modalTilte">User: <%= "#{@user.first_name} " "#{@user.last_name}"  %></h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class='modal-body'>
      <div class="field-group-inline row">
        <div class="field-label col-md-3">Email</div>
        <div class="col-md-8"><%= @user.email %></div>
      </div>

      <div class="field-group-inline row">
        <div class="field-label col-md-3">Last Sign In</div>
        <div class="col-md-8"><%= @user.last_sign_in_at.to_s(:medium) %></div>
      </div>

      <div class="field-group-inline row">
        <div class="field-label col-md-3">Confirmed At</div>
        <div class="col-md-8">$<%= @user.confirmed_at.to_s(:medium) %></div>
      </div>


      <div class="field-group-inline row" data-field="created">
        <div class="field-label col-md-3">Created at</div>
        <div class="col-md-8">
          <%= @user.created_at.to_s(:medium) %>
        </div>
      </div>
    <div class="field-group-inline row" data-field="updated">
      <div class="field-label col-md-3">Updated at</div>
      <div class="col-md-8">
        <%= @user.updated_at.to_s(:medium) %>
      </div>
    </div>
    <div class="modal-footer">
      <div class="actions col-md-12 text-center">
        <%= button_tag 'Close', {class: "btn btn-default", "data-dismiss" => "modal", id: 'btnClose'} %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('#btnClose').click(function() {
     $("#modal-window").modal("hide");
  });
});
</script>

app/views/users/_show_roles.html.erb
<div class="container">
  <div class="modal-content">
    <%= form_for @user, url: {action: "save_roles" }, method: "post", remote: true,
      html: { class: "edit_user_roles form-horizontal", id: "edit_user_roles_#{@user.id}" } do |f| %>
      <%#= f.hidden_field :lock_version %>
      <% new_role = heading_prefix == 'Edit' ? false : true %>
      <%#= hidden_field_tag("user[new_role]", new_role) %>
      <div class="modal-header">
        <h2><%= heading_prefix %> Roles<%= heading_prefix == 'Edit' ? ": #{@user.full_name}" : '' %></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- <%#= render partial: 'layouts/flash_messages', locals: {:context => :modal}  %> -->
      <div class="modal-body">

        <table class="table table-bordered table-hover table-striped" id="tblUserRoles">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Roles</th>
              <th scope="col">End Date</th>
            </tr>
          </thead>
          <tbody>
          <span class="fa fa-calendar-alt"></span>
            <%= render partial: "user_roles", locals: {allroles: @allroles} %>
          </tbody>
        </table>

     </div>
      <div class="modal-footer">
        <div class="actions text-center">
          <%= f.submit :Update, {class: "btn btn-success"} %>
          <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user_roles.html.erb
  <% test = [] %>
  <% unless allroles.blank? %>
    <% allroles.each do |ar| %>
      <tr id=<%=ar.id %> >
        <td><%= ar.id %></td>
        <% unless  @existing_roles.blank? %>
          <% @existing_roles.each do |er| %>
            <% if er[0] == ar.id %>
              <% test << ar.id %>
              <td>
                <%= check_box_tag "user[role_ids][]", ar.id, (checked = true if er[0] == ar.id), class: "cbox" %>
                <%= label_tag ar.name, ar.name, class: "control-label" %>
              </td>
              <td>
                <%= text_field_tag("user[end_dates][#{ar.id}]",
                                  er[1], class: "form-control myflatpickr") %>
              </td>
            <% end %>
        <% end %>
      <% end %>
      <% unless  test.include? ar.id %>
        <td>
          <%= check_box_tag "user[role_ids][]", ar.id, false, class: "cbox" %>
          <%= label_tag ar.name, ar.name, class: "control-label" %>
        </td>
        <td>
          <%= text_field_tag("user[end_dates][#{ar.id}]",
                            nil, class: "form-control myflatpickr") %>
        </td>
      <% end %>
    </tr>
    <% end %>
  <% end %>

<script type="text/javascript">
  flatpickr(".myflatpickr", {});
</script>

app/views/users/index.html.erb
<div class="container-fluid">
  <%= form_tag(users_path, method: 'get', id: 'search_user') do |f| %>
    <h1 class="page-header">
      Users
    </h1>
    <div class="row">
      <div class="col-sm-2">
        <%= search_field_tag :first_name, nil, class: 'form-control',
        placeholder: 'First Name', value: params[:first_name] %>
      </div>
      <div class="col-sm-2">
        <%= search_field_tag :last_name, nil, class: 'form-control',
        placeholder: 'Last Name', value: params[:last_name] %>
      </div>
      <div class="col-sm-2">
        <%= search_field_tag :email, nil, class: 'form-control',
        placeholder: 'Email', value: params[:email] %>
      </div>
      <div class="col-sm-2">
        <%= select_tag :approved, options_for_select(['True', 'False'],
        params[:approved].to_s), {prompt: "Approved", class: 'form-control selectpicker'} %>
      </div>
      <div class="col-sm-2">
          <%= submit_tag "Submit", class: 'btn btn-primary btn-md', :name => nil,
            id: 'log_submit_btn' %>
          <input type="button" value="Clear" id="clear_filter"
            class="btn btn-danger btn-md">
      </div>
    </div>
<% end %>
<br>
  <table class="table table-bordered table-hover table-striped" id="tblItem">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Approved</th>
        <th scope="col">Confirmed at</th>
        <th scope="col">Action(s)</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "row",  locals: { users: @users} %>
    </tbody>
  </table>
</div>
  <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
  <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#tblItem').DataTable();
  });

</script>

app/views/users/row.js.erb
// close the modal
$("#modal-window").modal("hide");
$(".row.row-msg").fadeOut().remove();
$(".messages").fadeOut().remove();
$('.modal').modal('hide');
var item = <%= @user.to_json.html_safe %>;
$("#statusModal-<%= @user.id %>").modal("hide");
$(".row.row-msg").fadeOut().remove();
$(".messages").fadeOut().remove();
<% if controller.action_name == "save_roles" %>
  $('#tblItem').after("<%= escape_javascript(render partial: 'layouts/flash_messages', locals: { :context => :inline} ) %>");
    <%#= escape_javascript('layouts/flash_messages', locals: {:context => :inline}) %>
<% end %>

app/views/users/show.js.erb
var contents = "<%= escape_javascript(render 'users/show') %>";

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);

app/views/users/show_roles.js.erb
var contents = "<%= escape_javascript(render partial: 'users/show_roles', locals: {url: edit_role_path, submit_label: 'Edit', heading_prefix: 'Edit', method: 'patch'}) %>";

$("#modal-window").modal();
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);

app/views/users/update_approve.js.erb
// close the modal
$('.modal').modal('hide');
var item = <%= @user.to_json.html_safe %>;
$("#statusModal-<%= @user.id %>").modal("hide");
$(".row.row-msg").fadeOut().remove();
$(".messages").fadeOut().remove();
<% if controller.action_name == "update_approve" %>
  $("#"+ item["id"] +"").replaceWith("<%= escape_javascript(render partial: 'row_item', locals: {user: @user} ) %>");
<% end %>