config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :users
  resources :items
  resources :stores
  resources :quotes
  # Role and Permission related
  resources :permissions
  resources :roles do
    get  'update_permissions'
    post 'save_permissions'
    patch 'save_permissions'
  end

  get '/users/:id/roles', controller: 'users', action: 'show_roles', as: 'show_roles'
  match '/users/:id/save_roles', to:'users#save_roles', via: [:patch, :post], as: 'user_roles_save'
  match '/users/:id/update_approve', to:'users#update_approve', via: [:patch, :post], as: 'user_approve'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/add_quotes/', controller: 'quotes', action: 'add_quote', as: 'add_quote'
end

app/models/role.rb
# Role model class, users belong to certain roles e.g.
# Senior Controller, Controller, Depot Manager, Depot Admin, Region Manager etc
# Through user_role_locations we determine what kind of access the current_user
# has throughout the application.
class Role < ApplicationRecord
  include Formatters

  has_paper_trail versions: { class_name: 'RoleVersion' }

  before_validation(on: [:create, :update]) do
    # self.name = self.name.titleize.strip unless self.name.blank?
    transform_titleize [:name]
    strip_whitespace [:name, :description]
  end

  has_and_belongs_to_many :permissions, :join_table => :role_permissions
  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :description, presence: true
  has_many :user_role_locations

  # case insensitive find eg. Role.ci_find("name", "Driver")
  scope :ci_find, lambda { |attribute, value| where("lower(#{attribute}) = ?", value.downcase).first }

  # Save permissions to role, note that we allow permissions to be completely
  # removed from a role.
  def save_role_permissions permission_ids, full_name
    # Find the role id first
    # Based on role_id delete eveything from role_permissions table
    # Add all the permission checked in the forms to the role_permissions table
    unless permission_ids.blank?
      perms = Permission.find(permission_ids)
      # self.permissions = [] # cannot use this as it does not trigger PaperTrail
      rrp = RolePermission.where(:role_id => self.id).destroy_all
      # We are deleting the permissions first and recreating it
      # Thus we dont need updated_by in role_permissions table
      perms.each do |p|
        rl = RolePermission.create!(:role_id => self.id,
            :permission_id => p.id,
            :created_by => full_name,
            :updated_by => full_name
            )
      end
    else
      # self.permissions = []  # cannot use this as it does not trigger PaperTrail
      rrp = RolePermission.where(:role_id => self.id).destroy_all
    end
  end

  # This will retrun true or false based on roles been assigned or not
  def has_role_been_assigned?
    # UserRoleLocation.find_by_role_id(self.id).blank? ? false : true
    # UserRoleLocation.where("role_id=? and (end_date <= (?) or end_date is ?)",
    #  self.id, date.now(), nil).blank? ? false : true
    # End date doesn't matter, record is not deleted after end date so we need
    # to keep the reference even after the end date
    UserRoleLocation.where("role_id=?", self.id).blank? ? false : true
  end

  private

  # Specifies the fields that have some auto formatting, we use this to distinqush
  # formatting changes vs real data changes when updates occur
  def formatted_fields
    {name: ['strip', 'titleize'], description: ['strip']}
  end


end

app/controllers/roles_controller.rb
# The Role Controller class facilitates the crud actions on
# role model.
# CRUD actions are triggered from within the permission index page
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action do set_active_main_menu "roles" end
  before_action :set_current_user

  # after_action :verify_authorized, only: [:index, :create, :update, :destroy, :update_permissions, :save_permissions]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ActionController::UnknownFormat, with: :Unknown_Format

  # Displays all roles
  def index
    @roles = Role.all.order(:name)
    authorize @roles
  end

  # Displays selected roles
  def show
    @role = Role.find(params[:id])
    # @roles = Role.paginate(page: params[:page], per_page: 10)
    @existing_perms_name = Role.find(params[:id]).permissions.collect{|r| r.name}.join ', '

    @permissions = Permission.all.order(:group_name, :name)
    @existing_perms = Role.find(params[:id]).permissions.pluck(:id)
    # just get groups with permissions
    groups = Role.find(params[:id]).permissions.pluck(:group_name).uniq.sort
    @perm_groups = {"Other" => []}
    groups.each do |g|
      @perm_groups[g] = []
    end
    @permissions.each do |p|
      if p.group_name.blank?
        @perm_groups["Other"] << p
      else
        # ignore those without key as they are not to be displayed
        if @perm_groups.key?(p.group_name)
          @perm_groups[p.group_name] << p
        end
      end
    end
  end  # def show ends here

  # New modal, gets triggered from within user page
  def new
    @role= Role.new
    @error_msg = @role.errors.messages
  end

  # Create saves the role
  def create
    @role = Role.new(role_params)
    @role.set_modifiers current_user
    if authorize @role
      if @role.save
        flash[:context] = "inline"
        flash[:success] = "Role '#{@role.name}' successfully created."
        flash[:success_id], flash[:row_id] = @role.id, @role.id
        render 'row'
      else
        flash.now[:error] = @role.errors.full_messages
        @error_msg = @role.errors.messages
        render 'new'
      end
    end
  end

  # Edit modal, gets triggered when press the Edit button next to a show
  def edit
    @role = Role.find(params[:id])
    @permissions = Permission.all
    @error_msg = @role.errors.messages
  end

  # Update saves the role
  def update
    @role = Role.find(params[:id])
    changed = @role.contains_changes?(role_params)
    @role.set_modifiers current_user if changed
    if authorize @role
      @current_user = current_user
      if changed && @role.update(role_params)
        flash[:context] = "inline"
        flash[:success] = "Role '#{@role.name}' successfully updated."
        flash[:success_id], flash[:row_id] = @role.id, @role.id
        render 'row'
      else
        @role.errors[:base] << "No changes made" unless changed
        flash.now[:error] = @role.errors.full_messages
        @error_msg = @role.errors.messages
        render 'edit'
      end
    end
  end

  # Destroy deletes the role
  # Deletes only if it is not assigned to permission
  def destroy
    @role = Role.find(params[:id])
    if authorize @role
      if @role.has_role_been_assigned?
        flash.now[:error] = "Cannot delete role when it is being assigned."
        render 'edit'
      else
        if @role.destroy
          flash.now[:notice] = "Role '#{@role.name}' successfully deleted"
          render 'row'
        end
      end
    end
  end

  # update permission for the selected role
  def update_permissions
    if authorize RolePermission
      @role = Role.find(params[:role_id])
      @permissions = Permission.all.order(:group_name, :name)
      @existing_perms = Role.find(params[:role_id]).permissions.pluck(:id)
      groups = Permission.all.group(:group_name).order(:group_name).pluck(:group_name)
      @perm_groups = {"Other" => []}
      groups.each do |g|
        @perm_groups[g] = []
      end
      @permissions.each do |p|
        if p.group_name.blank?
          @perm_groups["Other"] << p
        else
          @perm_groups[p.group_name] << p
        end
      end
      render 'permissions'
    end
  end

  # save permission for the selected role
  def save_permissions
    # Find the role id first
    # Based on role_id delete eveything from role_permissions table
    # Add all the permission checked in the forms to the role_permissions table
    if authorize RolePermission
      @role = Role.find(params[:role_id])
      @role.set_modifiers current_user
      if params[:role] && params[:role][:permission_ids]
        if @role.save_role_permissions params[:role][:permission_ids], current_user.full_name
          # flash[:notice] = "Permission(s) successfully assigned to the #{@role.name} role." unless @role.permissions.blank
          flash[:context] = "inline"
          flash.now[:success] = "Permission(s) successfully assigned to the #{@role.name} role."
          flash.now[:success_id], flash.now[:row_id] = @role.id, @role.id
          # TODO Should we explicitly require some kind of token value for permission removal?
          # flash[:notice] = "All permission(s) for the #{@role.name} role has been removed." if @role.permissions.blank?
        end
      else
        @role.save_role_permissions [], current_user.full_name
        # flash[:notice] = "All permission(s) for the #{@role.name} role has been removed."
        flash[:context] = "inline"
        flash.now[:success] = "All permission(s) for the #{@role.name} role has been removed."
        flash.now[:success_id], flash.now[:row_id] = @role.id, @role.id
      end
      # redirect_to :action => "index"
      render 'row'
    end
  end

  private

    # Whitelist the parameters we know/expect
    def role_params
      params.require(:role).permit(:name, :id, :description)
    end
    # Whitelist the parameters we know/expect for search
    def search_roles_params
      params.permit(:name, :description)
    end
end

app/views/roles/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for(:role, remote: true, url: url, method: method, html: {class: 'form-horizontal'}) do |f| %>
      <div class="modal-header">
          <h2><%= heading_prefix %> Role<%= heading_prefix == 'Edit' ? ": #{@role.name }" : '' %></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <%= render partial: 'layouts/flash_messages', locals: {:context => :modal}  %>
      <div class="modal-body">
        <div class="form-group required <%= @error_msg[:name].blank? ? "" : "has-error" %>">
          <%= f.label :name, class: "control-label col-md-3" %>
          <div class="col-md-7">
            <%= f.text_field :name, {autofocus: true, class: "form-control", required: true} %>
          </div>
        </div>
        <div class="form-group required <%= @error_msg[:description].blank? ? "" : "has-error" %>">
          <%= f.label :description, class: "control-label col-md-3" %>
          <div class="col-md-7">
            <%= f.text_area :description, {class: "form-control", required: true, style: "min-width: 80%"} %>
          </div>
        </div>

      </div>
      <div class="form-group">
       <div class="col-md-12 col-md-offset-3">
         <span class="help-block"><span class="mandatory">*</span> denotes required field</span>
       </div>
      </div>
      <div class="modal-footer">
        <div class="actions text-center">
          <%= f.submit submit_label, {class: "btn btn-default btn-success"} %>
          <%= f.button 'Cancel', {class: "btn btn-default", "data-dismiss" => "modal"} %>
          <% if (controller.action_name == "edit") && (!@role.has_role_been_assigned?) %>
            <%= f.button 'Delete', {id: "delete", class: "btn btn-danger", "type" => "button",
              "data-toggle" => "collapse", "data-target" => "#confirm-delete-pane"} %>
            <div id="confirm-delete-pane" class="confirm-delete-pane collapse col-md-12 text-center">
              <p>Please confirm that you want to delete Role: <%= @role.name %></p>
              <%= link_to 'Confirm Delete', role_path(@role.id),
                {method: 'delete', id: 'confirm-delete', class: 'btn btn-danger btn-success', remote: true} %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/roles/_permissions.html.erb
<div class="container">
  <div class="modal-content">
    <%= form_for @role, url: {action: "save_permissions" }, method: "post", remote: true,
      html: { class: "save_permissions form-horizontal", id: "savepermissions#{@role.id}" } do |f| %>
      <div class="modal-header">
        <h2><%= heading_prefix %> Role<%= heading_prefix == 'Edit' ? ": #{@role.name }" : '' %></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%#= render partial: 'layouts/flash_messages', locals: {:context => :modal}  %>
      <div class="modal-body scrollable">
        <div class="form-group" >
          <!-- Nav tabs -->
          <div class="col-sm-3">
            <div class="nav tabs-left RolesHeader" role="tablist" id ="myTab">
              <% @perm_groups.each do |grp, perms|%>
                <% unless perms.blank? %>
                  <% grp_name = grp.delete(' ') %>
                  <!-- Deleting special character -->
                  <% grp_name.gsub!(/[^0-9A-Za-z]/, '') unless grp_name.blank? %>
                  <div class="nav-item RolesSubHeader">
                    <a class="nav-link" data-toggle="tab" href="#panel-group-<%= grp_name %>"
                      role="tab" id="<%= grp_name %>"><%= grp %></a>
                  </div>
                <% end %>
              <% end %>
              <div class="nav-item RolesSubHeader">
                <a class="nav-link active" data-toggle="tab" href="#panel-all"
                  role="tab" id="All"> All</a>
              </div>
            </div>
          </div>
          <!-- Tab panels -->
          <div class="col-md-8">
            <div class="tab-content">
              <% @perm_groups.each do |g, perms|%>
                <% grp_class = g.delete(' ') unless g.blank? %>
                <!-- Deleting special character -->
                <% grp_class.gsub!(/[^0-9A-Za-z]/, '') unless grp_class.blank? %>
                <div id="panel-group-<%= grp_class %>" class="tab-pane fade" role="tabpanel">
                  <% perms.each do |perm| %>
                    <% checked_flag = @existing_perms.index(perm.id).nil? ? false : true %>
                    <div class="col-md-4">
                      <%= check_box_tag "role[permission_ids][]", perm.id, checked_flag,
                        {class: "cbox", id: "role_permission_ids_#{perm.id}", "data-group" => "#{grp_class}"} %>
                        <%= f.label "permission_ids_#{perm.id}", perm.name, class: "role-perms-label" %>
                    </div>
                  <% end %>
                </div>
              <% end %>
              <div id="panel-all" class="tab-pane fade in active" role="tabpanel">
                <% @permissions.each do |perm| %>
                  <% checked_flag = @existing_perms.index(perm.id).nil? ? false : true %>
                  <div class="col-md-4">
                    <%= check_box_tag "role[permission_ids][]", perm.id, checked_flag,
                      {class: "cbox", id: "role_permission_ids_#{perm.id}", "data-group" => "all"} %>
                    <%= f.label "permission_ids_#{perm.id}", perm.name, {class: "role-perms-label"} %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <%= hidden_field "role[id]", "role_id" %>
        </div>
      </div>
      <div class="modal-footer">
        <div class="actions col-md-12 text-center">
          <%= f.submit submit_label, {class: "btn btn-default btn-success",
            id: "save_role_perms_#{@role.id}"} %>
          <%= f.button 'Cancel', {class: "btn btn-default", "data-dismiss" => "modal"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    $(".modal-body #panel-all input[type='checkbox']").change(event, function(){
      var id = this.id;
      var state = $("#panel-all " + "input#" + id + ":checked").length;
      sync_checkbox("others", id, state);
    });

    $(".modal-body div[id^='panel-group-'] input[type='checkbox']").change(event, function(){
      var id = this.id;
      var state = $("div[id^='panel-group-'] " + "input#" + id + ":checked").length;
      sync_checkbox("all", id, state);
    });
  });

  function sync_checkbox(group, id, state) {
    if (group == "all") {
      ele = "#panel-all input#" + id;
    } else {
      ele = "div[id^='panel-group-'] input#" + id;
    }

    if (state == 0) {
      // uncheck
      $(ele).prop("checked", false);
    } else {
      // check
      $(ele).prop("checked",true);
    }
  }

  $(".RolesSubHeader").on("click", function() {
    $(".RolesSubHeader").css("background", "#f1f1f1");
    $(this).css("background", "#b5e899");
  });

</script>

app/views/roles/_row.html.erb
<% unless roles.blank? %>
  <% roles.each do |r| %>
  <tr id=<%= r.id %> >
    <td><%= r.id %></td>
    <td><%= r.name %></td>
    <td><%= r.description %></td>

    <td style="text-align:center">
      <div>
        <% if policy(Role).show? %>
          <%= link_to 'Show', role_path(r),  {remote: true,
            'data-target' => '#modal-window',
            class: 'btn btn-primary btn-sm'} %>
        <% end %>
        <% if policy(Role).update? %>
          <%= link_to "Edit",  edit_role_path(r),  {
            remote: true,
            'data-target' => '#modal-window', 'class' => 'btn btn-primary btn-sm'} %>
        <% end %>
        <% if policy(RolePermission).assign_roles? %>
          <%= link_to "Permissions", role_update_permissions_path(r.id), {
              remote: true,
              'data-target' => '#modal-window', 'class' => 'btn btn-primary btn-sm'} %>
        <% end %>
      </div>
    </td>

    <td>
      Created at <%= r.created_at.to_s(:medium) %> by <%= r.created_by %><br>
      Updated at <%= r.updated_at.to_s(:medium) %> by <%= r.updated_by %>
    </td>
  </tr>
  <% end %>
<% end %>

app/views/roles/_row_item.html.erb
<%# this is trigger only after either update or show %>
<% unless role.blank? %>
<tr style='background-color: #d4edda;' id=<%= role.id %> >
  <td><%= role.id %></td>
  <td><%= role.name %></td>
  <td><%= role.description %></td>

  <td style="text-align:center">
    <div>
      <% if policy(Role).show? %>
        <%= link_to 'Show', role_path(role),  {remote: true,
          'data-target' => '#modal-window',
          class: 'btn btn-primary btn-sm'} %>
      <% end %>
      <% if policy(Role).update? %>
        <%= link_to "Edit",  edit_role_path(role),  {
          remote: true,
          'data-target' => '#modal-window', 'class' => 'btn btn-primary btn-sm'} %>
      <% end %>
      <% if policy(RolePermission).assign_roles? %>
        <%= link_to "Permissions", role_update_permissions_path(role), {
            remote: true,
            'data-target' => '#modal-window', 'class' => 'btn btn-primary btn-sm'} %>
      <% end %>
    </div>
  </td>

  <td>Created at <%= role.created_at.to_s(:medium) %> by <%= role.created_by %><br>
  Updated at <%= role.updated_at.to_s(:medium) %> by <%= role.updated_by %></td>

</tr>
<% end %>

app/views/roles/_show.html.erb
<div class="container">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Role: <%= @role.name %></h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div>
      <ol style="list-style-type: inherit;"">
        <li> <p> <%= @role.description %></p></li>
        <li>  <p>Created at: <%= @role.created_at.to_s(:medium) %> by <%= @role.created_by %></p> </li>
        <li>  <p>Updated at: <%= @role.updated_at.to_s(:medium) %> by <%= @role.updated_by %></p> </li>
      </ol>
    </div>

    <div class="modal-body scrollable">
      <div class="form-group" >
        <h3>Permission(s)</h3>
        <!-- Nav tabs -->
        <div class="col-sm-3">
          <div class="nav tabs-left RolesHeader" role="tablist" id ="myTab">
            <% perms_cnt = 0 %>
            <% @perm_groups.each do |grp, perms|%>
              <% unless perms.blank? %>
                <% grp_name = grp.delete(' ') %>
                <!-- Deleting special character -->
                <% grp_name.gsub!(/[^0-9A-Za-z]/, '') unless grp_name.blank? %>
                <div class="nav-item RolesSubHeader">
                  <a class="nav-link" data-toggle="tab" href="#panel-group-<%= grp_name %>"
                    role="tab" id="<%= grp_name %>"><%= grp %></a>
                </div>
                <% perms_cnt = perms_cnt + perms.count %>
              <% end %>
            <% end %>
            <% if perms_cnt > 0 %>
              <div class="nav-item RolesSubHeader">
                <a class="nav-link active" data-toggle="tab" href="#panel-all"
                  role="tab" id="All"> All</a>
              </div>
            <% end %>
          </div>
        </div>
        <!-- Tab panels -->
        <div class="col-md-8">
          <div class="tab-content">
            <% @perm_groups.each do |g, perms|%>
              <% grp_class = g.delete(' ') unless g.blank? %>
              <!-- Deleting special character -->
              <% grp_class.gsub!(/[^0-9A-Za-z]/, '') unless g.blank? %>
              <div id="panel-group-<%= grp_class %>" class="tab-pane fade" role="tabpanel">
                <% perms.each do |perm| %>
                  <% checked_flag = @existing_perms.index(perm.id).nil? ? false : true %>
                  <% if checked_flag %>
                    <div class="col-md-4">
                      <span class="fa fa-check-square" title="<%= perm.name %>" ></span>
                      <%= label perm.name, perm.name, class: "perms-label" %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
            <div id="panel-all" class="tab-pane fade in active" role="tabpanel">
              <% @permissions.each do |perm| %>
                <% checked_flag = @existing_perms.index(perm.id).nil? ? false : true %>
                <% if checked_flag %>
                  <div class="col-md-4">
                    <span class="fa fa-check-square" title="<%= perm.name %>" ></span>
                    <%= label perm.name, perm.name, class: "perms-label" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <div class="actions text-center">
        <%= button_tag 'Close', {class: "btn btn-default", "data-dismiss" => "modal"} %>
      </div>
    </div>
  </div>
</div>

app/views/roles/destroy.html.erb
This is a dummy page (destroy.html.erb). Can be deleted because the controller
redirect to the index page once the record is deleted. This page will only show
if the redirect_to is not there. For example, you want to show a confirmation page
here.

app/views/roles/edit.js.erb
var contents = "<%= escape_javascript(render partial: 'roles/form', locals: {url: role_path, submit_label: 'Update', heading_prefix: 'Edit', method: 'patch'}) %>";

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);

$('.confirm-delete-pane').on("shown.bs.collapse", function() {
  $("#delete").attr("disabled", "disabled");
});

app/views/roles/index.html.erb
<!-- This index page shows the summary of all roles -->
<div class="container-fluid">
  <h1 class="page-header">Roles
  </h1>
  <div>
    <div class="col-sm-1">
      <% if policy(Role).create? %>
        <%= link_to "Add Role", new_role_path,
          {'class' => 'btn btn-success', 'remote' => true,
          'data-target' => '#modal-window', 'id' => 'Add_btn'} %>
          <hr>
      <% end %>

    </div>
  </div>

  <% unless @roles.blank? %>
    <table class="table table-bordered table-hover table-striped" id="tblItem">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Action(s)</th>
          <th scope="col">TimeStamp)</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "row",  locals: { roles: @roles} %>
      </tbody>
    </table>
  <% end %>
</div>

<div class="col-md-2">
  <div class="hidden context-right-side-pane">
  </div>
</div>
</div>

<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $('#tblItem').DataTable();
});

</script>

app/views/roles/new.js.erb
var contents = "<%= escape_javascript(render partial: 'roles/form', locals: {url: roles_path, submit_label: 'Add', heading_prefix: 'Add', method: 'post'}) %>";

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action')
})
$("#modal-window").html(contents);

app/views/roles/permissions.js.erb
var contents = "<%= escape_javascript(render partial: 'roles/permissions', locals: {url: role_update_permissions_path, submit_label: 'Update', heading_prefix: 'Edit', method: 'patch'}) %>";
// remove any previous flash messages
$(".row.row-msg").fadeOut().remove();
$(".messages").fadeOut().remove();

$("#modal-window").modal({backdrop: 'static', keyboard: false});
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);

app/views/roles/row.js.erb
// close the modal
$("#modal-window").modal("hide");
$(".row.row-msg").fadeOut().remove();
$(".messages").fadeOut().remove();
<% if controller.action_name == "index" %>
  // Placeholder maybe when we update states belonging to countries this changes
<% elsif controller.action_name == "create" %>
  var item = <%= @role.to_json.html_safe %>;
  $('#tblItem tbody tr:first').before("<%= escape_javascript(render partial: 'row_item', locals: {role: @role} ) %>");
<% elsif controller.action_name == "update" || controller.action_name =="save_permissions"%>
var item = <%= @role.to_json.html_safe %>;
 $("#"+ item["id"] +"").replaceWith("<%= escape_javascript(render partial: 'row_item', locals: { role: @role} ) %>");
<% elsif controller.action_name == "destroy" %>
  var item = <%= @role.to_json.html_safe %>;
  $("#"+ item["id"] +"").fadeOut("normal", function() {
        $(this).remove();
  });
<% end %>

app/views/roles/show.js.erb
var contents = "<%= escape_javascript(render 'roles/show') %>";

$("#modal-window").modal();
$("#modal-window").on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget);
  var action = button.data('action');
})

$("#modal-window").html(contents);