config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :users
  resources :items
  resources :stores
  resources :quotes
  # Role and Permission related
  resources :permissions
  resources :roles do
    get  'update_permissions'
    post 'save_permissions'
    patch 'save_permissions'
  end

  get '/users/:id/roles', controller: 'users', action: 'show_roles', as: 'show_roles'
  match '/users/:id/save_roles', to:'users#save_roles', via: [:patch, :post], as: 'user_roles_save'
  match '/users/:id/update_approve', to:'users#update_approve', via: [:patch, :post], as: 'user_approve'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/add_quotes/', controller: 'quotes', action: 'add_quote', as: 'add_quote'
end

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>

  <% # add bootstrap alert classes
    alert_classes = {'alert' => 'alert-warning',
      'notice' => 'alert-info',
      'error' => 'alert-danger',
      'success' => 'alert-success'}

    # check if we need a container class
    container = ''
    if current_user
      if defined?(context).nil?
        container = 'container-fluid'
      end
    end
  %>
  <% unless container.blank? %>
    <div class="<%= container %>">
  <% end %>
    <div class="messages">
      <% flash.each do |k, v| %>
        <% if alert_classes.has_key? k %>
          <div class="alert <%= alert_classes[k] %>">
            <% if v.acts_like?('string') %>
              <%= v %>
            <% else %>
              <ul>
                <% v.each do |m| %>
                  <li><%= m %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% unless container.blank? %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_menu_generate_quote.html.erb
<li class="dropdown <%= @active_menu == "quote" ? "active" : "" %>">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"
    role="button" aria-haspopup="true" aria-expanded="false">
      Quote
  </a>
  <ul class="dropdown-menu navmenu-nav">
    <li><%= link_to 'Generate Quote', quotes_path if policy(Role).index? %></li>
  </ul>
</li>

app/views/layouts/_menu_item.html.erb
<li class="dropdown  <%= @active_menu == "items" ? "active" : "" %>">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"
    role="button" aria-haspopup="true" aria-expanded="false">
      Item
  </a>
  <ul class="dropdown-menu navmenu-nav">
    <li><%= link_to 'Item Management', items_path if policy(Item).index? %></li>
  </ul>
</li>

app/views/layouts/_menu_role_permission.html.erb
<li class="dropdown <%= @active_menu == "roles" ? "active" : "" %>">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"
    role="button" aria-haspopup="true" aria-expanded="false">
      Roles & Permissions
  </a>
  <ul class="dropdown-menu navmenu-nav">
    <li><%= link_to 'Role Management', roles_path if policy(Role).index? %></li>
    <li><%= link_to 'Permission Management', permissions_path if policy(Permission).index? %></li>
  </ul>
</li>

app/views/layouts/_menu_store.html.erb
<li class="dropdown  <%= @active_menu == "users" ? "active" : "" %>">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"
    role="button" aria-haspopup="true" aria-expanded="false">
      Store
  </a>
  <ul class="dropdown-menu navmenu-nav">
      <li><%= link_to 'Store Management', stores_path if policy(Store).index? %></li>
  </ul>
</li>

app/views/layouts/_menu_user.html.erb
<li class="dropdown  <%= @active_menu == "users" ? "active" : "" %>">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"
    role="button" aria-haspopup="true" aria-expanded="false">
      User
  </a>
  <ul class="dropdown-menu">
      <li><%= link_to 'User Management', users_path if policy(User).index? %></li>
  </ul>
</li>

app/views/layouts/_navigation.html.erb
<% if current_user %>
<!--Side navigation bar  -->
  <!-- <div class="navmenu navmenu-default navmenu-fixed-left offcanvas"> -->
  <nav class="navbar navbar-inverse">
    <div class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-left">
       <%= render partial: 'layouts/menu_user' if policy(User).index? %>
       <%= render partial: 'layouts/menu_item' if policy(Item).index? %>
       <%= render partial: 'layouts/menu_store' %>
       <%= render partial: 'layouts/menu_role_permission' if policy(Role).index? || policy(Permission).index? %>
       <%= render partial: 'layouts/menu_generate_quote' %>
     </ul>
   </div>
</nav>
<hr>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PresQuote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <% if current_user %>
      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
      <!-- Fixed horizotnal menu bar  -->
      <nav class="navbar navbar-expand-lg navbar-light navbar-bgcolor">
          <div id="main">
            <button class="openbtn">☰</button>
          </div>
          <div class="ml-auto">
            <%= link_to "#{current_user.first_name}'s Profile", nil, method: 'post', class: "btn btn-info" %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete', class: "btn btn-success" %>
          </div>
      </nav>
  <% end %>

    <div id="mySidebar" class="sidebar">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
      <%= render partial: 'layouts/navigation' %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>

    <div id="modal-window" class="modal fade" tabindex="-1"; role="dialog" aria-labelledby="PTP Master Static Pricing" aria-hidden="true">
    </div>
    <%= yield %>
  </body>
</html>


<script type="text/javascript">
  $(document).ready(function () {
    $('.openbtn').on('click', function(){
      openNav();
    });

    $('.closebtn').on('click', function(){
      closeNav();
    });
  });

  function openNav() {
    $('#mySidebar').css('width', '15%');
    $('#main').css('marginLeft',  "15%");
    $('.openbtn').hide();
  }

  function closeNav() {
    $('#mySidebar').css('width', '0%');
    $('#main').css('marginLeft',  "0%");
    $('.openbtn').show();
  }

</script>